apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
  namespace: tanilytics-query
data:
  QUERY_SERVICE_PORT: "8081"
  SPRING_PROFILES_ACTIVE: docker
  REDIS_HOST: redis
  REDIS_PORT: 6379
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: 6379
  CLICKHOUSE_URL: jdbc:clickhouse://clickhouse.tanilytics-storage.svc.cluster.local:8123/default
  CLICKHOUSE_DATABASE: default
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317