apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  namespace: tanilytics-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: tanilytics/query-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: query-service-config
            - secretRef:
                name: query-service-secret