apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: tanilytics-query
spec:
  selector:
    app: query-service
  ports:
    - name: http
      port: 8081        # Service port
      targetPort: 8081  # Container port
  type: ClusterIP