name: tanilytics
networks:
  tanilytics_network:
    driver: bridge
volumes:
  redpanda-0: null
  redpanda-1: null
  redpanda-2: null
  postgres-data: null
  redis-data: null
  hadoop-namenode-data: null
  hadoop-datanode-data: null
services:
  ##################
  # Redpanda Brokers #
  ##################
  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:${REDPANDA_0_KAFKA_PORT}
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:${REDPANDA_0_KAFKA_PORT}
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:${REDPANDA_0_PROXY_PORT}
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:${REDPANDA_0_PROXY_PORT}
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:${REDPANDA_0_SCHEMA_PORT}
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode ${REDPANDA_MODE}
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp ${REDPANDA_SMP}
      - --default-log-level=${REDPANDA_LOG_LEVEL}
    image: ${REDPANDA_IMAGE}
    container_name: redpanda-0
    # Sets the username and password of the bootstrap SCRAM superuser
    # See https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/manual/production/production-deployment/#bootstrap-a-user-account
    environment:
      RP_BOOTSTRAP_USER: "${REDPANDA_SUPERUSER}:${REDPANDA_PASSWORD}"
    volumes:
      - redpanda-0:/var/lib/redpanda/data
      - ./bootstrap.yml:/etc/redpanda/.bootstrap.yaml
    networks:
      - tanilytics_network
    ports:
      - ${REDPANDA_0_SCHEMA_PORT}:${REDPANDA_0_SCHEMA_PORT}
      - ${REDPANDA_0_PROXY_PORT}:${REDPANDA_0_PROXY_PORT}
      - ${REDPANDA_0_KAFKA_PORT}:${REDPANDA_0_KAFKA_PORT}
      - ${REDPANDA_0_ADMIN_PORT}:9644
    healthcheck:
      test:
        [
          "CMD",
          "rpk",
          "cluster",
          "info",
          "-X",
          "user=${REDPANDA_SUPERUSER}",
          "-X",
          "pass=${REDPANDA_PASSWORD}",
        ]
      interval: 10s
      timeout: 15s
      retries: 10
  redpanda-1:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:${REDPANDA_1_KAFKA_PORT}
      - --advertise-kafka-addr internal://redpanda-1:9092,external://localhost:${REDPANDA_1_KAFKA_PORT}
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:${REDPANDA_1_PROXY_PORT}
      - --advertise-pandaproxy-addr internal://redpanda-1:8082,external://localhost:${REDPANDA_1_PROXY_PORT}
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:${REDPANDA_1_SCHEMA_PORT}
      - --rpc-addr redpanda-1:33145
      - --advertise-rpc-addr redpanda-1:33145
      - --mode ${REDPANDA_MODE}
      - --smp ${REDPANDA_SMP}
      - --default-log-level=${REDPANDA_LOG_LEVEL}
      - --seeds redpanda-0:33145
    image: ${REDPANDA_IMAGE}
    container_name: redpanda-1
    environment:
      RP_BOOTSTRAP_USER: "${REDPANDA_SUPERUSER}:${REDPANDA_PASSWORD}"
    volumes:
      - redpanda-1:/var/lib/redpanda/data
      - ./bootstrap.yml:/etc/redpanda/.bootstrap.yaml
    networks:
      - tanilytics_network
    ports:
      - ${REDPANDA_1_SCHEMA_PORT}:${REDPANDA_1_SCHEMA_PORT}
      - ${REDPANDA_1_PROXY_PORT}:${REDPANDA_1_PROXY_PORT}
      - ${REDPANDA_1_KAFKA_PORT}:${REDPANDA_1_KAFKA_PORT}
      - ${REDPANDA_1_ADMIN_PORT}:9644
    healthcheck:
      test:
        [
          "CMD",
          "rpk",
          "cluster",
          "info",
          "-X",
          "user=${REDPANDA_SUPERUSER}",
          "-X",
          "pass=${REDPANDA_PASSWORD}",
        ]
      interval: 10s
      timeout: 15s
      retries: 10
    depends_on:
      - redpanda-0
  redpanda-2:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:${REDPANDA_2_KAFKA_PORT}
      - --advertise-kafka-addr internal://redpanda-2:9092,external://localhost:${REDPANDA_2_KAFKA_PORT}
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:${REDPANDA_2_PROXY_PORT}
      - --advertise-pandaproxy-addr internal://redpanda-2:8082,external://localhost:${REDPANDA_2_PROXY_PORT}
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:${REDPANDA_2_SCHEMA_PORT}
      - --rpc-addr redpanda-2:33145
      - --advertise-rpc-addr redpanda-2:33145
      - --mode ${REDPANDA_MODE}
      - --smp ${REDPANDA_SMP}
      - --default-log-level=${REDPANDA_LOG_LEVEL}
      - --seeds redpanda-0:33145
    image: ${REDPANDA_IMAGE}
    container_name: redpanda-2
    environment:
      RP_BOOTSTRAP_USER: "${REDPANDA_SUPERUSER}:${REDPANDA_PASSWORD}"
    volumes:
      - redpanda-2:/var/lib/redpanda/data
      - ./bootstrap.yml:/etc/redpanda/.bootstrap.yaml
    networks:
      - tanilytics_network
    ports:
      - ${REDPANDA_2_SCHEMA_PORT}:${REDPANDA_2_SCHEMA_PORT}
      - ${REDPANDA_2_PROXY_PORT}:${REDPANDA_2_PROXY_PORT}
      - ${REDPANDA_2_KAFKA_PORT}:${REDPANDA_2_KAFKA_PORT}
      - ${REDPANDA_2_ADMIN_PORT}:9644
    healthcheck:
      test:
        [
          "CMD",
          "rpk",
          "cluster",
          "info",
          "-X",
          "user=${REDPANDA_SUPERUSER}",
          "-X",
          "pass=${REDPANDA_PASSWORD}",
        ]
      interval: 10s
      timeout: 15s
      retries: 10
    depends_on:
      - redpanda-0
  ####################
  # Redpanda Console #
  ####################
  console:
    container_name: redpanda-console
    image: ${CONSOLE_IMAGE}
    networks:
      - tanilytics_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml && /app/console'
    volumes:
      - ./config:/tmp/config/
    environment:
      CONFIG_FILEPATH: ${CONFIG_FILEPATH:-/tmp/config.yml}
      CONSOLE_CONFIG_FILE: |
        # Configure a connection to the Redpanda cluster
        # See https://docs.redpanda.com/current/console/config/connect-to-redpanda/
        kafka:
          brokers: ["redpanda-0:9092"]
          sasl:
            enabled: true
            impersonateUser: true
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda-0:8081","http://redpanda-1:8081","http://redpanda-2:8081"]
          authentication:
            impersonateUser: true
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644","http://redpanda-1:9644","http://redpanda-2:9644"]
            authentication:
              basic:
                username: ${REDPANDA_SUPERUSER}
                password: ${REDPANDA_PASSWORD}
              impersonateUser: false
        authentication:
          jwtSigningKey: ${CONSOLE_JWT_SIGNING_KEY}
          basic:
            enabled: true
        authorization:
          roleBindings:
          - roleName: admin
            users:
              - loginType: basic
                name: ${REDPANDA_SUPERUSER}
    ports:
      - ${CONSOLE_PORT}:8080
    depends_on:
      redpanda-0:
        condition: service_healthy
      createtopic:
        condition: service_completed_successfully
  ############
  # Redis #
  ############
  redis:
    image: ${REDIS_IMAGE}
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - tanilytics_network
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  ################
  # HDFS NameNode #
  ################
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    environment:
      CLUSTER_NAME: tanilytics
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: 1
    volumes:
      - hadoop-namenode-data:/hadoop/dfs/name
    networks:
      - tanilytics_network
    ports:
      - ${HDFS_NAMENODE_WEB_PORT}:9870
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870/"]
      interval: 15s
      timeout: 5s
      retries: 5

  ################
  # HDFS DataNode #
  ################
  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    volumes:
      - hadoop-datanode-data:/hadoop/dfs/data
    networks:
      - tanilytics_network
    ports:
      - ${HDFS_DATANODE_WEB_PORT}:9864
    depends_on:
      namenode:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9864/"]
      interval: 15s
      timeout: 5s
      retries: 5
  ################
  # PostgreSQL #
  ################
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tanilytics_network
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
  ###################
  # Auth Service #
  ###################
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRY: ${JWT_ACCESS_EXPIRY}
      JWT_REFRESH_EXPIRY: ${JWT_REFRESH_EXPIRY}
      JWT_INTERNAL_AUDIENCE: ${JWT_INTERNAL_AUDIENCE}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${JAVA_OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - tanilytics_network
    ports:
      - ${AUTH_SERVICE_PORT}:8082
    depends_on:
      redpanda-0:
        condition: service_healthy
      redis:
        condition: service_healthy
      namenode:
        condition: service_healthy

  ####################
  # Query Service #
  ####################
  query-service:
    build:
      context: ../query-service
      dockerfile: Dockerfile
    container_name: query-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      HDFS_NAMENODE: hdfs://namenode:9000
      HDFS_USER: ${HDFS_USER}
      HDFS_BASE_PATH: ${HDFS_BASE_PATH}
      AUTH_SERVICE_URL: http://auth-service:8082
      JWT_SECRET: ${JWT_SECRET}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${JAVA_OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - tanilytics_network
    ports:
      - ${QUERY_SERVICE_PORT}:8081
    depends_on:
      redis:
        condition: service_healthy

  ####################
  # rpk container to create raw-events and dlq topics #
  # See https://docs.redpanda.com/current/reference/rpk/rpk-topic/rpk-topic-create/
  ####################
  createtopic:
    image: ${REDPANDA_IMAGE}
    networks:
      - tanilytics_network
    entrypoint: /bin/sh
    command:
      - -c
      - |
        rpk topic create ${RAW_EVENTS_TOPIC} \
          --if-not-exists \
          --partitions ${RAW_EVENTS_PARTITIONS} \
          --replicas ${RAW_EVENTS_REPLICAS} \
          -c cleanup.policy=${RAW_EVENTS_CLEANUP_POLICY} \
          -c retention.ms=${RAW_EVENTS_RETENTION_MS} \
          -c retention.bytes=${RAW_EVENTS_RETENTION_BYTES} \
          -c compression.type=${RAW_EVENTS_COMPRESSION} \
          -X user=${REDPANDA_SUPERUSER} \
          -X pass=${REDPANDA_PASSWORD} \
          -X brokers=redpanda-0:9092 && \
        rpk topic create ${DLQ_TOPIC} \
          --if-not-exists \
          --partitions ${DLQ_PARTITIONS} \
          --replicas ${DLQ_REPLICAS} \
          -c cleanup.policy=${DLQ_CLEANUP_POLICY} \
          -c retention.ms=${DLQ_RETENTION_MS} \
          -c compression.type=${DLQ_COMPRESSION} \
          -X user=${REDPANDA_SUPERUSER} \
          -X pass=${REDPANDA_PASSWORD} \
          -X brokers=redpanda-0:9092
    depends_on:
      redpanda-0:
        condition: service_healthy
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - tanilytics_network
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/jaeger:2.16.0
    container_name: jaeger
    networks:
      - tanilytics_network
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  ###############
  # Ingestion #
  ###############
  ingestion:
    build:
      context: ../ingestion
      dockerfile: Dockerfile
    container_name: ingestion
    networks:
      - tanilytics_network
    ports:
      - "${INGESTION_PORT}:3000"
    environment:
      - INGESTION_PORT=${INGESTION_PORT}
      - REDPANDA_BROKERS=${REDPANDA_BROKERS}
      - REDPANDA_SASL_USER=${REDPANDA_SASL_USER}
      - REDPANDA_SASL_PASSWORD=${REDPANDA_SASL_PASSWORD}
      - REDPANDA_SASL_MECHANISM=${REDPANDA_SASL_MECHANISM}
      - PRODUCER_TOPIC=${PRODUCER_TOPIC}
      - PRODUCER_BATCH_MAX_BYTES=${PRODUCER_BATCH_MAX_BYTES}
      - PRODUCER_LINGER=${PRODUCER_LINGER}
      - PRODUCER_MAX_BUFFERED_RECORDS=${PRODUCER_MAX_BUFFERED_RECORDS}
      - PRODUCER_RECORD_RETRIES=${PRODUCER_RECORD_RETRIES}
      - PRODUCER_RETRY_TIMEOUT=${PRODUCER_RETRY_TIMEOUT}
      - REDIS_URL=${REDIS_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - BLOOM_FILTER_CAPACITY=${BLOOM_FILTER_CAPACITY}
      - BLOOM_FILTER_ERROR_RATE=${BLOOM_FILTER_ERROR_RATE}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    depends_on:
      redpanda-0:
        condition: service_healthy
      redis:
        condition: service_healthy

  ################
  # Processing #
  ################
  processing:
    build:
      context: ../processing
      dockerfile: Dockerfile
    container_name: processing
    networks:
      - tanilytics_network
    environment:
      - PROCESSING_PORT=${PROCESSING_PORT}
      - REDPANDA_BROKERS=${REDPANDA_BROKERS}
      - REDPANDA_SASL_USER=${REDPANDA_SASL_USER}
      - REDPANDA_SASL_PASSWORD=${REDPANDA_SASL_PASSWORD}
      - REDPANDA_SASL_MECHANISM=${REDPANDA_SASL_MECHANISM}
      - DLQ_TOPIC=${DLQ_TOPIC}
      - DLQ_PRODUCER_BATCH_MAX_BYTES=${DLQ_PRODUCER_BATCH_MAX_BYTES}
      - DLQ_PRODUCER_LINGER=${DLQ_PRODUCER_LINGER}
      - DLQ_PRODUCER_MAX_BUFFERED_RECORDS=${DLQ_PRODUCER_MAX_BUFFERED_RECORDS}
      - DLQ_PRODUCER_RECORD_RETRIES=${DLQ_PRODUCER_RECORD_RETRIES}
      - DLQ_PRODUCER_RETRY_TIMEOUT=${DLQ_PRODUCER_RETRY_TIMEOUT}
      - HDFS_NAMENODE_ADDR=${HDFS_NAMENODE_ADDR}
      - HDFS_USER=${HDFS_USER}
      - HDFS_BASE_PATH=${HDFS_BASE_PATH}
      - CONSUMER_BATCH_SIZE=${CONSUMER_BATCH_SIZE}
      - CONSUMER_BATCH_TIMEOUT=${CONSUMER_BATCH_TIMEOUT}
      - REDIS_URL=${REDIS_URL}
      - ANONYMIZATION_SALT=${ANONYMIZATION_SALT}
      - LOG_LEVEL=${LOG_LEVEL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - CONSUMER_GROUP=${CONSUMER_GROUP}
      - CONSUMER_TOPIC=${CONSUMER_TOPIC}
      - CONSUMER_RESET_OFFSET=${CONSUMER_RESET_OFFSET}
      - CONSUMER_FETCH_MIN_BYTES=${CONSUMER_FETCH_MIN_BYTES}
      - CONSUMER_FETCH_MAX_BYTES=${CONSUMER_FETCH_MAX_BYTES}
      - CONSUMER_FETCH_MAX_WAIT=${CONSUMER_FETCH_MAX_WAIT}
      - CONSUMER_FETCH_MAX_PARTITION_BYTES=${CONSUMER_FETCH_MAX_PARTITION_BYTES}
      - CONSUMER_BLOCK_REBALANCE_ON_POLL=${CONSUMER_BLOCK_REBALANCE_ON_POLL}
      - CONSUMER_MAX_CONCURRENT_FETCHES=${CONSUMER_MAX_CONCURRENT_FETCHES}
      - GEOIP_DB_PATH=${GEOIP_DB_PATH}
    depends_on:
      redpanda-0:
        condition: service_healthy
      redis:
        condition: service_healthy