apiVersion: v1
kind: Service
metadata:
  name: clickhouse-native
  namespace: tanilytics-storage
spec:
  selector:
    app: clickhouse
  ports:
    - name: native
      port: 9000
      targetPort: 9000
  type: ClusterIP