apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: tanilytics-storage
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:25.3
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: CLICKHOUSE_DB
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_DB
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - clickhouse-client --host 127.0.0.1 --user "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" --database "$CLICKHOUSE_DB" --query "SELECT 1"
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - clickhouse-client --host 127.0.0.1 --user "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" --database "$CLICKHOUSE_DB" --query "SELECT 1"
            initialDelaySeconds: 40
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi