apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-config"
  namespace: {{ .Values.namespace }}
data:
  PROCESSING_PORT: "{{ .Values.configMap.data.PROCESSING_PORT }}"
  REDPANDA_BROKERS: "{{ .Values.configMap.data.REDPANDA_BROKERS }}"
  REDPANDA_SASL_MECHANISM: "{{ .Values.configMap.data.REDPANDA_SASL_MECHANISM }}"

  DLQ_TOPIC: "{{ .Values.configMap.data.DLQ_TOPIC }}"
  DLQ_PRODUCER_BATCH_MAX_BYTES: "{{ .Values.configMap.data.DLQ_PRODUCER_BATCH_MAX_BYTES }}"
  DLQ_PRODUCER_LINGER: "{{ .Values.configMap.data.DLQ_PRODUCER_LINGER }}"
  DLQ_PRODUCER_MAX_BUFFERED_RECORDS: "{{ .Values.configMap.data.DLQ_PRODUCER_MAX_BUFFERED_RECORDS }}"
  DLQ_PRODUCER_RECORD_RETRIES: "{{ .Values.configMap.data.DLQ_PRODUCER_RECORD_RETRIES }}"
  DLQ_PRODUCER_RETRY_TIMEOUT:  "{{ .Values.configMap.data.DLQ_PRODUCER_RETRY_TIMEOUT }}"

  CLICKHOUSE_ADDRS: "{{ .Values.configMap.data.CLICKHOUSE_ADDRS }}"
  CLICKHOUSE_DATABASE: "{{ .Values.configMap.data.CLICKHOUSE_DATABASE }}"
  CLICKHOUSE_DIAL_TIMEOUT: "{{ .Values.configMap.data.CLICKHOUSE_DIAL_TIMEOUT }}"
  CLICKHOUSE_MAX_OPEN_CONNS: "{{ .Values.configMap.data.CLICKHOUSE_MAX_OPEN_CONNS }}"
  CLICKHOUSE_MAX_IDLE_CONNS: "{{ .Values.configMap.data.CLICKHOUSE_MAX_IDLE_CONNS }}"
  CLICKHOUSE_CONN_OPEN_STRATEGY: "{{ .Values.configMap.data.CLICKHOUSE_CONN_OPEN_STRATEGY }}"

  CH_BATCH_SIZE: "{{ .Values.configMap.data.CH_BATCH_SIZE }}"
  CH_BATCH_TIMEOUT: "{{ .Values.configMap.data.CH_BATCH_TIMEOUT }}"

  LOG_LEVEL: "{{ .Values.configMap.data.LOG_LEVEL }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.configMap.data.OTEL_EXPORTER_OTLP_ENDPOINT }}"

  CONSUMER_GROUP: "{{ .Values.configMap.data.CONSUMER_GROUP }}"
  CONSUMER_TOPIC: "{{ .Values.configMap.data.CONSUMER_TOPIC }}"
  CONSUMER_RESET_OFFSET: "{{ .Values.configMap.data.CONSUMER_RESET_OFFSET }}"
  CONSUMER_FETCH_MIN_BYTES: "{{ .Values.configMap.data.CONSUMER_FETCH_MIN_BYTES }}"
  CONSUMER_FETCH_MAX_BYTES: "{{ .Values.configMap.data.CONSUMER_FETCH_MAX_BYTES }}"
  CONSUMER_FETCH_MAX_WAIT: "{{ .Values.configMap.data.CONSUMER_FETCH_MAX_WAIT }}"
  CONSUMER_FETCH_MAX_PARTITION_BYTES: "{{ .Values.configMap.data.CONSUMER_FETCH_MAX_PARTITION_BYTES }}"
  CONSUMER_BLOCK_REBALANCE_ON_POLL: "{{ .Values.configMap.data.CONSUMER_BLOCK_REBALANCE_ON_POLL }}"
  CONSUMER_MAX_CONCURRENT_FETCHES: "{{ .Values.configMap.data.CONSUMER_MAX_CONCURRENT_FETCHES }}"

  GEOIP_DB_PATH: "{{ .Values.configMap.data.GEOIP_DB_PATH }}"
  REDIS_URL: "{{ .Values.configMap.data.REDIS_URL }}"

