#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
  #name: processing-metrics
  #namespace: tanilytics-processing
  #labels:
    # This label is what Prometheus uses to discover ServiceMonitors
    #release: kube-prometheus-stack
#spec:
  #selector:
    #matchLabels:
      #app: processing-service
  #endpoints:
    #- port: metrics      
      #path: /metrics
      #interval: 15s
  #namespaceSelector:
    #matchNames:
      #- tanilytics-processing