apiVersion: v1
kind: Service
metadata:
  name: processing
  namespace: tanilytics-processing
spec:
  selector:
    app: processing
  ports:
    - name: http
      port: 3001        # Service port
      targetPort: 3000  # Container port
  type: ClusterIP