job:
  name: clickhouse-migrations
  backoffLimit: 3
  restartPolicy: Never
  image: migrate/migrate:v4.19.1
  env:
    - name: CLICKHOUSE_USER
      valueFrom:
        secretKeyRef:
          name: clickhouse
          key: username
    - name: CLICKHOUSE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: clickhouse
          key: password
    - name: CLICKHOUSE_HOST
      value: "clickhouse.tanilytics-storage.svc.cluster.local"
  command:
    - /bin/sh
    - -ec
    - |
      migrate -verbose \
        -path /migrations \
        -database "clickhouse://${CLICKHOUSE_HOST}:9000?username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}&x-multi-statement=true" \
        up
  volumeMounts:
    - name: migrations
      mountPath: /migrations
  volumes:
    - name: migrations
      configMap:
        name: clickhouse-migrations
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

