apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: tanilytics-query
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8082        # Service port
      targetPort: 8082  # Container port
  type: ClusterIP