apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "query-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "query-service.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "query-service.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ include "query-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "query-service.fullname" . }}-config
            - secretRef:
                name: {{ include "query-service.fullname" . }}-secret
