apiVersion: v1
kind: Service
metadata:
  name: {{ include "query-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "query-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
  type: {{ .Values.service.type }}