apiVersion: v1
kind: Service
metadata:
  name: ingestion
  namespace: tanilytics-ingest
spec:
  selector:
    app: ingestion
  ports:
    - name: http
      port: 3000        # Service port
      targetPort: 3000  # Container port
  type: ClusterIP