namespace: tanilytics-query
replicaCount: 1

image:
  tag: latest

service:
  containerPort: 8081
  port: 8081
  type: ClusterIP

spring:
  profilesActive: docker

redis:
  host: redis-master.tanilytics-ingest.svc.cluster.local
  port: 6379

clickhouse:
  host: clickhouse.tanilytics-storage.svc.cluster.local
  port: 8123
  database: default

otel:
  endpoint: http://otel-collector:4317
