apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "{{ .Values.database.username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
  REDIS_PASSWORD: "{{ .Values.redis.password }}"
  JWT_SECRET: "{{ .Values.jwt.secret }}"
