apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "auth-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}        # Service port
      targetPort: {{ .Values.service.containerPort }}  # Container port
  type: {{ .Values.service.type }}
